[package]
name = "amazon_kinesis_client"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.51.0"
base64 = "0.13.1"
base64-serde = "0.6.1"
chrono = {version = "0.4.22", features = ["serde"] }
eyre = "0.6.8"
serde = {version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
