[package]
name = "amazon_kinesis_client"
version = "0.3.1"
edition = "2021"

[dependencies]
base64 = "0.13.1"
base64-serde = "0.6.1"
eyre = "0.6.8"
serde = {version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.37"
